### 멤버 생성 marco - json
POST localhost:8080/members
Content-Type: application/json

{
  "id": "marco",
  "name": "마르코",
  "password": "4444",
  "age": 444,
  "role": "admin"
}

### 멤버 생성 jsj - csv
POST localhost:8080/members
Content-Type: text/csv

jsj,조승주,1234,25,member

### 멤버 조회 marco xml
GET localhost:8080/members/marco
Accept: application/xml

### 멤버 조회 jsj - csv
GET localhost:8080/members/jsj
Accept: text/csv

### 멤버 조회 전체 - xml
GET localhost:8080/members
Accept: application/xml

### 차단 될 예제 유저 추가
POST localhost:8080/members
Content-Type: text/csv

hus,한의석,1234,26,member